Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Python312\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
from module.dataTransformer import combineData
from module.fetcher import fetchDataMysql, fetchDataPg

data_pg = fetchDataPg("SELECT petal_length, petal_width, species FROM iris_table")
data_my = fetchDataMysql("SELECT sepal_length, sepal_width FROM iris_table")

iris_df = combineData(data1=data_my, data2=data_pg)

print("Missing Value:", iris_df.isnull().sum(), end="\n")
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mMySQLInterfaceError[0m                       Traceback (most recent call last)
File [1;32mC:\Python312\Lib\site-packages\mysql\connector\connection_cext.py:354[0m, in [0;36mCMySQLConnection._open_connection[1;34m(self)[0m
[0;32m    353[0m [38;5;28;01mtry[39;00m:
[1;32m--> 354[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_cmysql[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcnx_kwargs[49m[43m)[49m
[0;32m    355[0m     [38;5;28mself[39m[38;5;241m.[39m_cmysql[38;5;241m.[39mconverter_str_fallback [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_converter_str_fallback

[1;31mMySQLInterfaceError[0m: Can't connect to MySQL server on 'localhost:3306' (10061)

The above exception was the direct cause of the following exception:

[1;31mDatabaseError[0m                             Traceback (most recent call last)
Cell [1;32mIn[1], line 6[0m
[0;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmodule[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfetcher[39;00m [38;5;28;01mimport[39;00m fetchDataMysql, fetchDataPg
[0;32m      5[0m data_pg [38;5;241m=[39m fetchDataPg([38;5;124m"[39m[38;5;124mSELECT petal_length, petal_width, species FROM iris_table[39m[38;5;124m"[39m)
[1;32m----> 6[0m data_my [38;5;241m=[39m [43mfetchDataMysql[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mSELECT sepal_length, sepal_width FROM iris_table[39;49m[38;5;124;43m"[39;49m[43m)[49m
[0;32m      8[0m iris_df [38;5;241m=[39m combineData(data1[38;5;241m=[39mdata_my, data2[38;5;241m=[39mdata_pg)
[0;32m     10[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mMissing Value:[39m[38;5;124m"[39m, iris_df[38;5;241m.[39misnull()[38;5;241m.[39msum(), end[38;5;241m=[39m[38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m)

File [1;32mD:\Matkul\Tugas_Matkul\Semester5\PSD\PSD\module\fetcher.py:17[0m, in [0;36mfetchDataMysql[1;34m(query)[0m
[0;32m     16[0m [38;5;28;01mdef[39;00m [38;5;21mfetchDataMysql[39m(query):
[1;32m---> 17[0m     connection [38;5;241m=[39m [43mmysqlConnection[49m[43m([49m[43m)[49m
[0;32m     18[0m     cursor [38;5;241m=[39m connection[38;5;241m.[39mcursor()
[0;32m     20[0m     cursor[38;5;241m.[39mexecute(query)

File [1;32mD:\Matkul\Tugas_Matkul\Semester5\PSD\PSD\module\fetcher.py:5[0m, in [0;36mmysqlConnection[1;34m()[0m
[0;32m      4[0m [38;5;28;01mdef[39;00m [38;5;21mmysqlConnection[39m():
[1;32m----> 5[0m     [38;5;28;01mreturn[39;00m [43mmyconnector[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m
[0;32m      6[0m [43m        [49m[43mhost[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mlocalhost[39;49m[38;5;124;43m"[39;49m[43m,[49m
[0;32m      7[0m [43m        [49m[43mport[49m[38;5;241;43m=[39;49m[38;5;241;43m3306[39;49m[43m,[49m
[0;32m      8[0m [43m        [49m[43muser[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mroot[39;49m[38;5;124;43m"[39;49m[43m,[49m
[0;32m      9[0m [43m        [49m[43mpassword[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m"[39;49m[43m,[49m
[0;32m     10[0m [43m        [49m[43mdatabase[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43miris_db[39;49m[38;5;124;43m"[39;49m
[0;32m     11[0m [43m    [49m[43m)[49m

File [1;32mC:\Python312\Lib\site-packages\mysql\connector\pooling.py:322[0m, in [0;36mconnect[1;34m(*args, **kwargs)[0m
[0;32m    319[0m         [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(ERROR_NO_CEXT)
[0;32m    321[0m [38;5;28;01mif[39;00m CMySQLConnection [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m use_pure:
[1;32m--> 322[0m     [38;5;28;01mreturn[39;00m [43mCMySQLConnection[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[0;32m    323[0m [38;5;28;01mreturn[39;00m MySQLConnection([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [1;32mC:\Python312\Lib\site-packages\mysql\connector\connection_cext.py:142[0m, in [0;36mCMySQLConnection.__init__[1;34m(self, **kwargs)[0m
[0;32m    140[0m [38;5;28;01mif[39;00m kwargs:
[0;32m    141[0m     [38;5;28;01mtry[39;00m:
[1;32m--> 142[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[0;32m    143[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:
[0;32m    144[0m         [38;5;28mself[39m[38;5;241m.[39mclose()

File [1;32mC:\Python312\Lib\site-packages\mysql\connector\abstracts.py:1604[0m, in [0;36mMySQLConnectionAbstract.connect[1;34m(self, **kwargs)[0m
[0;32m   1601[0m     [38;5;28mself[39m[38;5;241m.[39mconfig([38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m   1603[0m [38;5;28mself[39m[38;5;241m.[39mdisconnect()
[1;32m-> 1604[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_open_connection[49m[43m([49m[43m)[49m
[0;32m   1606[0m charset, collation [38;5;241m=[39m (
[0;32m   1607[0m     kwargs[38;5;241m.[39mpop([38;5;124m"[39m[38;5;124mcharset[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m),
[0;32m   1608[0m     kwargs[38;5;241m.[39mpop([38;5;124m"[39m[38;5;124mcollation[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m),
[0;32m   1609[0m )
[0;32m   1610[0m [38;5;28;01mif[39;00m charset [38;5;129;01mor[39;00m collation:

File [1;32mC:\Python312\Lib\site-packages\mysql\connector\connection_cext.py:360[0m, in [0;36mCMySQLConnection._open_connection[1;34m(self)[0m
[0;32m    358[0m [38;5;28;01mexcept[39;00m MySQLInterfaceError [38;5;28;01mas[39;00m err:
[0;32m    359[0m     [38;5;28;01mif[39;00m [38;5;28mhasattr[39m(err, [38;5;124m"[39m[38;5;124merrno[39m[38;5;124m"[39m):
[1;32m--> 360[0m         [38;5;28;01mraise[39;00m get_mysql_exception(
[0;32m    361[0m             err[38;5;241m.[39merrno, msg[38;5;241m=[39merr[38;5;241m.[39mmsg, sqlstate[38;5;241m=[39merr[38;5;241m.[39msqlstate
[0;32m    362[0m         ) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[0;32m    363[0m     [38;5;28;01mraise[39;00m InterfaceError([38;5;28mstr[39m(err)) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[0;32m    365[0m [38;5;28mself[39m[38;5;241m.[39m_do_handshake()

[1;31mDatabaseError[0m: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)

